//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.12 at 01:39:24 PM EAT 
//


package com.alookatsoapapisinspringboot.school;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.alookatsoapapisinspringboot.school package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.alookatsoapapisinspringboot.school
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllStudentRequest }
     * 
     */
    public GetAllStudentRequest createGetAllStudentRequest() {
        return new GetAllStudentRequest();
    }

    /**
     * Create an instance of {@link GetStudentByIdResponse }
     * 
     */
    public GetStudentByIdResponse createGetStudentByIdResponse() {
        return new GetStudentByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UploadStudentInfo }
     * 
     */
    public UploadStudentInfo createUploadStudentInfo() {
        return new UploadStudentInfo();
    }

    /**
     * Create an instance of {@link UpdateStudentRequest }
     * 
     */
    public UpdateStudentRequest createUpdateStudentRequest() {
        return new UpdateStudentRequest();
    }

    /**
     * Create an instance of {@link GetStudentByIdRequest }
     * 
     */
    public GetStudentByIdRequest createGetStudentByIdRequest() {
        return new GetStudentByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteStudentResponse }
     * 
     */
    public DeleteStudentResponse createDeleteStudentResponse() {
        return new DeleteStudentResponse();
    }

    /**
     * Create an instance of {@link GetAllStudentResponse }
     * 
     */
    public GetAllStudentResponse createGetAllStudentResponse() {
        return new GetAllStudentResponse();
    }

    /**
     * Create an instance of {@link UploadStudentRequest }
     * 
     */
    public UploadStudentRequest createUploadStudentRequest() {
        return new UploadStudentRequest();
    }

    /**
     * Create an instance of {@link UpdateStudentResponse }
     * 
     */
    public UpdateStudentResponse createUpdateStudentResponse() {
        return new UpdateStudentResponse();
    }

    /**
     * Create an instance of {@link DeleteStudentRequest }
     * 
     */
    public DeleteStudentRequest createDeleteStudentRequest() {
        return new DeleteStudentRequest();
    }

    /**
     * Create an instance of {@link UploadStudentResponse }
     * 
     */
    public UploadStudentResponse createUploadStudentResponse() {
        return new UploadStudentResponse();
    }

}
