//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.12 at 01:39:24 PM EAT 
//


package com.alookatsoapapisinspringboot.school;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="studentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="UploadStudentInfo" type="{http://www.alookatSOAPAPIsInSpringBoot.com/school}UploadStudentInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "studentId",
    "uploadStudentInfo"
})
@XmlRootElement(namespace="http://www.alookatSOAPAPIsInSpringBoot.com/school",name = "updateStudentRequest")
public class UpdateStudentRequest {
    @XmlElement(namespace="http://www.alookatSOAPAPIsInSpringBoot.com/school",name = "UploadStudentInfo", required = true)
    protected long studentId;
    @XmlElement(namespace="http://www.alookatSOAPAPIsInSpringBoot.com/school",name = "UploadStudentInfo", required = true)
    protected UploadStudentInfo uploadStudentInfo;

    /**
     * Gets the value of the studentId property.
     * 
     */
    public long getStudentId() {
        return studentId;
    }

    /**
     * Sets the value of the studentId property.
     * 
     */
    public void setStudentId(long value) {
        this.studentId = value;
    }

    /**
     * Gets the value of the uploadStudentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UploadStudentInfo }
     *     
     */
    public UploadStudentInfo getUploadStudentInfo() {
        return uploadStudentInfo;
    }

    /**
     * Sets the value of the uploadStudentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadStudentInfo }
     *     
     */
    public void setUploadStudentInfo(UploadStudentInfo value) {
        this.uploadStudentInfo = value;
    }

}
